# Site settings
title: Open Source OAuth 2.0 & OpenID Connect Documentation
email: alexandre.leborgne.83@gmail.com
description: >
  Open Source OAuth 2.0 & OpenID Connect Documentation

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://php-guard.github.io # the base hostname & protocol for your site
git_address: https://php-guard.github.io
#git_edit_address: https://php-guard.github.io

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Paris
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
